name: EnderVault
version: 2.0.1
main: me.pepsiplaya.endervaults.EnderVault
author: Pepsiplaya
description: A plugin that provides a limited-size ender vault for players
api-version: 1.19

commands:
  ev:
    description: Opens the ender vault
    usage: /ev open
    aliases: [endervault]